Introduction
------------

This book introduces ontology building using the OWL2 ontology language, and
the Tawny-OWL library. Ontologies are a method for representing knowledge,
generally, but not necessarily, about the world around us. It is then possible
to check that the representation is consistent, as well as drawing conclusions
about new knowledge. They are generally used in complex, knowledge-rich areas
of knowledge, including biomedicine.

Many ontology development tools provide a Graphical User Interface, through
which the ontology developer adds the various entities involved in building an
ontology. However, many ontologies contain large and repetitive sections; for
these, ontology development teams often fall back to generating parts of their
ontology programmatically. Tawny-OWL takes a different approach where ontology
development in a domain-specific language (DSL) embedded in a full programming
language. For structurally simple parts of an ontology, the various components
of an ontology can be specified using the default convienient and simple
Tawny-OWL syntax; for structurally complex parts, new syntax and new patterns
can be built, extending the environment as a core part of ontology
development.

This form of programmatic ontology development is still young. At the moment,
we have used it to produce large ontologies that would have been difficult
using any other technique. However, we also hope that we can also support
easier integration of knowledge-rich structures into applications, so that
ontological data structures can be come a standard part of the programmers
toolkit.





//
// Local Variables:
// linked-buffer-init: linked-buffer-wing-init
// End:
//
